version: "3"

services:
  bookmarks-server:
    container_name: bookmarks-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 80
    networks:
      - default
    environment:
      - VIRTUAL_HOST=klaxbookmarks.erminea.fr
      - LETSENCRYPT_HOST=klaxbookmarks.erminea.fr
      - LETSENCRYPT_EMAIL=ermineaweb@gmail.com
      - NODE_ENV=production
      - PORT=80
      - ITEM_PER_PAGES=3

networks:
  default:
    external:
      name: webproxy
